language: c

# Based from: https://github.com/greghendershott/travis-racket

# Optional: Remove to use Travis CI's older infrastructure.
sudo: true
dist: trusty


env:
  global:
    # Supply a global RACKET_DIR environment variable. This is where
    # Racket will be installed. A good idea is to use ~/racket because
    # that doesn't require sudo to install and is therefore compatible
    # with Travis CI's newer container infrastructure.
    - RACKET_DIR=~/racket
  matrix:
    # Supply at least one RACKET_VERSION environment variable. This is
    # used by the install-racket.sh script (run at before_install,
    # below) to select the version of Racket to download and install.
    #
    # Supply more than one RACKET_VERSION (as in the example below) to
    # create a Travis-CI build matrix to test against multiple Racket
    # versions.
    # - RACKET_VERSION=6.8
    # - RACKET_VERSION=RELEASE
    # - RACKET_VERSION=6.9
    - RACKET_VERSION=HEAD

matrix:
  allow_failures:
#   - env: RACKET_VERSION=HEAD
  fast_finish: true

before_install:
  # libmlt6
  - sudo add-apt-repository -y ppa:jonathonf/ffmpeg-3
  - sudo add-apt-repository -y ppa:jonathonf/tesseract
  - sudo apt-get -qq update
  - sudo apt-get install -y ffmpeg
  - sudo apt-get instsall -y libav-tools
  - sudo apt-get install -y libavcodec-dev
  - sudo apt-get install -y libavcodec-extra
  - sudo apt-get install -y libavformat-dev
  - sudo apt-get install -y libavutil-dev
  - sudo apt-get install -y libswscale-dev
  - sudo apt-get install -y ladspa-sdk
  - sudo apt-get install -y libgdk-pixbuf2.0-*
  - sudo apt-get install -y frei0r-plugins*
  - sudo apt-get install libdc1394-*
  # Turn off the irrelevant libdc1394 warning
  - sudo ln /dev/null /dev/raw1394
  # racket
  - git clone https://github.com/greghendershott/travis-racket.git ~/travis-racket
  - cat ~/travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us
  # xvfb, enables gtk
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

install:
 - raco pkg install --deps search-auto -n video

before_script:

# Here supply steps such as raco make, raco test, etc.  You can run
# `raco pkg install --deps search-auto` to install any required
# packages without it getting stuck on a confirmation prompt.
script:
 - raco test -p video

after_success:
 - raco setup --check-pkg-deps --pkgs video
 - raco pkg install --deps search-auto cover cover-codecov cover-coveralls
 - raco cover -b -f codecov -f coveralls -d $TRAVIS_BUILD_DIR/coverage .
